name: reproduction

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: pwd
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - run: git --version
      - run: env
      - run: whoami
      - run: ls -la
      - run: pwd
     
