name: reproduction

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - run: git --version
      - run: env
      - uses: actions/checkout@v3
